#!/bin/bash

# protect against invocations from script's own directory
if [ -f `basename $0` ] ; then
	echo "It seems you are running this script from the tools directory. Please run it from the website's main directory."
	exit 1
fi

export GEM_HOME=${PWD}/gems
export PATH=${GEM_HOME}/bin:${PATH}

bundle exec compass compile --force wp-content/themes/%THEME_SLUG%/