#!/bin/bash

# protect against invocations from script's own directory
if [ -f `basename $0` ] ; then
	echo "It seems you are running this script from the tools directory. Please run it from the website's main directory."
	exit 1
fi

export GEM_HOME=${PWD}/gems
export PATH=${GEM_HOME}/bin:${PATH}

CSS=`find wp-content/themes/%THEME_SLUG%/ -iname '*.css' -o -iname '*.scss' -exec git log -1 --format=%H {} +`
JS=`find wp-content/themes/%THEME_SLUG%/ -iname '*.js' -exec git log -1 --format=%H {} +`

cat >${PWD}/local-versions.php <<EOL
<?php
define('LOCAL_CSS_VERSION', '${CSS}');
define('LOCAL_JS_VERSION', '${JS}');
?>
EOL